### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by LSYS** [appeler/naampy#2]
Hi there, I encountered an error while importing:
```python
from naampy import in_rolls_fn_gender
```
![image](https://user-images.githubusercontent.com/10510571/176615727-c2f78312-5de3-4633-8f9a-dcf60c6ed5bc.png)

@rajashekar 

Seems like a tensorflow versioning issue.
I can replicate the same error by doing
```python
from keras.preprocessing.sequence import pad_sequences
```
which is solved by doing this instead:
```python
from keras_preprocessing.sequence import pad_sequences
```

I'm on tensorflow 2.9
![image](https://user-images.githubusercontent.com/10510571/176616806-fc203b71-5404-44b7-82d5-329643d9156d.png)

**Comment by rajashekar** [comment]
@LSYS - Thanks for reporting this. 

I freezed the tf version to 2.8.x in naampy https://pypi.org/project/naampy/0.4.1/ , please uninstall and install the package to get the latest changes.
